### ISSUE TITLE
Bug: Settings Page Overrides Other Plugin Settings Page

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ColorManager#18]
ColorManager settings page is shown when going to [MatomoConnector](https://github.com/aljawaid/MatomoConnector) settings.
```
// Extra Page - Routes
        //  - Example: $this->route->addRoute('/my/custom/route', 'myController', 'show', 'PluginNameExampleStudlyCaps');
        $this->route->addRoute('/settings/:url', 'ColorManagerController', 'show', 'ColorManager');
```
```
// MATOMO SETTINGS Page - Routes
        $this->route->addRoute('/settings/matomo', 'MatomoConnectorController', 'show', 'MatomoConnector');
```

When I go to settings in the MatomoCOnnector, the browser url is correct, but the screen shows the ColorManager settings page.

Any idea what is going on?

**Comment by aljawaid** [comment]
Definitely a problem with ColorManager.... after removing it,, the other plugin was fine

**Comment by creecros** [comment]
interesting

**Comment by creecros** [comment]
i cannot replicate

**Comment by aljawaid** [comment]
Oh crap what on earth does that error mean.

**Comment by creecros** [comment]
it means you cannot call this function like so:
`Kanboard\Plugin\MatomoConnector\Plugin::getPluginVersion($plugin);`

**Comment by aljawaid** [comment]
> it means you cannot call this function like so: `Kanboard\Plugin\MatomoConnector\Plugin::getPluginVersion($plugin);`
> 
> and even if you could `$plugin` is undefined.
- yeah, that just got fixed https://github.com/aljawaid/ColorManager/issues/18

> i am curious, and don't take offense, i don't mean it negatively I am truly just curious...how are you not seeing these errors?
- I check apache error logs, thats the only thing I know. I saw a different `undefined` error in the log for this morning, which thankfully was easy to fix.
- 
But your error above, never showed up at all.

Even after the undefined fix, I have the same issue

**Comment by creecros** [comment]
shows up right on the settings pagae at the bottom:
![image](https://user-images.githubusercontent.com/26339368/209832067-e4be8974-d83a-4eed-925e-bb9a899050e4.png)

**Comment by aljawaid** [comment]
> shows up right on the settings pagae at the bottom: ![image](https://user-images.githubusercontent.com/26339368/209832067-e4be8974-d83a-4eed-925e-bb9a899050e4.png)

I cant get access to the page because of the colromanager showing up instead, maybe thats why that error not rendering for me.... if i uninstall the colormanager its fine, but no error... maybe because i fixed the undefined variable.... but the static method i dont know how to/if i should fix as the 
```
<?php
        $pluginVersion = Kanboard\Plugin\MatomoConnector\Plugin::getPluginVersion();
        $pluginName = Kanboard\Plugin\MatomoConnector\Plugin::getPluginName();
        $pluginHomepage = Kanboard\Plugin\MatomoConnector\Plugin::getPluginHomepage();
?>
```
does work now

**Comment by aljawaid** [comment]
> `Fatal error: Uncaught Error: Non-static method Kanboard\Plugin\MatomoConnector\Plugin::getPluginVersion() cannot be called statically in /var/www/app/plugins/MatomoConnector/Template/config/settings.php:113 Stack trace: #0 /var/www/app/app/Core/Template.php(83): include() #1 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render() #2 /var/www/app/app/Helper/LayoutHelper.php(129): Kanboard\Helper\LayoutHelper->subLayout() #3 /var/www/app/plugins/MatomoConnector/Controller/MatomoConnectorController.php(26): Kanboard\Helper\LayoutHelper->config() #4 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Plugin\MatomoConnector\Controller\MatomoConnectorController->show() #5 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #6 /var/www/app/index.php(9): Kanboard\Core\Controller\Runner->execute() #7 {main} thrown in /var/www/app/plugins/MatomoConnector/Template/config/settings.php on line 113`

https://stackoverflow.com/questions/70422951/fatal-error-uncaught-error-non-static-method-primarykey-cannot-be-called-sta
suggests: `so you has to use -> instead of :: to call the methods`

**so should i do:**
```
<?php
        $pluginVersion = Kanboard\Plugin\MatomoConnector\Plugin->getPluginVersion();
        $pluginName = Kanboard\Plugin\MatomoConnector\Plugin->getPluginName();
        $pluginHomepage = Kanboard\Plugin\MatomoConnector\Plugin->getPluginHomepage();
        ?>
```

even though the code works now

**Comment by aljawaid** [comment]
> i cannot replicate
@creecros so if you have both plugins installed, you have no issues getting to both settings' pages?

**Comment by creecros** [comment]
> > i cannot replicate
> > @creecros so if you have both plugins installed, you have no issues getting to both settings' pages?

correct, i have no issues
![test3](https://user-images.githubusercontent.com/26339368/209835314-eaf8d403-1359-4590-a1d9-4c75e97d8ad6.gif)

**Comment by aljawaid** [comment]
strange... is there a cache file or directory in kanboard that I can delete?

_I will try without the routing when I get home tonight to see if that has anything to do with it_

**Comment by creecros** [comment]
> > `Fatal error: Uncaught Error: Non-static method Kanboard\Plugin\MatomoConnector\Plugin::getPluginVersion() cannot be called statically in /var/www/app/plugins/MatomoConnector/Template/config/settings.php:113 Stack trace: #0 /var/www/app/app/Core/Template.php(83): include() #1 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render() #2 /var/www/app/app/Helper/LayoutHelper.php(129): Kanboard\Helper\LayoutHelper->subLayout() #3 /var/www/app/plugins/MatomoConnector/Controller/MatomoConnectorController.php(26): Kanboard\Helper\LayoutHelper->config() #4 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Plugin\MatomoConnector\Controller\MatomoConnectorController->show() #5 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #6 /var/www/app/index.php(9): Kanboard\Core\Controller\Runner->execute() #7 {main} thrown in /var/www/app/plugins/MatomoConnector/Template/config/settings.php on line 113`
> 
> https://stackoverflow.com/questions/70422951/fatal-error-uncaught-error-non-static-method-primarykey-cannot-be-called-sta suggests: `so you has to use -> instead of :: to call the methods`
> 
> **so should i do:**
> 
> ```
> <?php
>         $pluginVersion = Kanboard\Plugin\MatomoConnector\Plugin->getPluginVersion();
>         $pluginName = Kanboard\Plugin\MatomoConnector\Plugin->getPluginName();
>         $pluginHomepage = Kanboard\Plugin\MatomoConnector\Plugin->getPluginHomepage();
>         ?>
> ```
> 
> even though the code works now

that wont work either. and no the code is not correct now.

I am unsure how to call those methods, but I can figure out how to get the info you are looking for.
This will work for plugin name:
`$pluginName = $this->app->getPluginName();`

the others im still trying to figure out.

**Comment by aljawaid** [comment]
so it is definitely ColorManager, I got the same issue with KanboardSupport, but NOT PluginManager (which uses the core `/extensions` url route)

**Comment by creecros** [comment]
Ok got it. 

**1st**
 You need to add this code to `show()` in your controller
`use Kanboard\Core\Plugin\Installer;`

```
public function show()
    {
        $this->response->html($this->helper->layout->config('matomoConnector:config/settings', array(
            'plugins' => $this->pluginLoader->getPlugins(),
            'title' => 'MatomoConnector &#10562; '.t('Settings'),
        )));
    }
```

Then in the settings template you can now use:
```
        <?php
        $pluginName = $this->app->getPluginName();
        $pluginVersion = $plugins[$pluginName]->getPluginVersion();
        $pluginHomepage = $plugins[$pluginName]->getPluginHomepage();
        ?>
```

**Comment by creecros** [comment]
> so it is definitely ColorManager, I got the same issue with KanboardSupport, but NOT PluginManager (which uses the core `/extensions` url route)
> 
> so it seems, on my plugins with routes, colormanager overrides the page. the other plugins do work (matomo codes shows up in the page)... its just the settings pages

Again, I cannot reproduce. Before you go buck wild on fixing something, make sure its not "your" KB thats broken.
Is it a fresh install? Latest Version? Etc...

**Comment by aljawaid** [comment]
Application version: 1.2.20
    PHP version: 7.4.3
    PHP SAPI: apache2handler
    HTTP Client: cURL
    OS version: Linux 5.4.0-91-generic
    Database driver: mysql
    Database version: 5.7.36
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0

**Comment by creecros** [comment]
ok, so i don't get it with matomo, but i am getting it with Kanboard Support. Now the question is why...

**Comment by aljawaid** [comment]
Even more weird lol... Rules out the kanboard. I'm suspecting urls or the controller.

**Comment by creecros** [comment]
its making more and more sense and less at the same time....

**Comment by creecros** [comment]
ya, i don't know, it makes no sense. I tried workarounds, but there is nothing, and you can't use `t('color-manager');` in the plugin.php, because the locale has not loaded yet, so it won't translate. I'm out of ideas. just make it static.

**Comment by aljawaid** [comment]
OK so did you try without the translation? Did that work?

**Comment by creecros** [comment]
yes, works as static. on my end at least.

**Comment by creecros** [comment]
that said, you have a ton of warnings in "KanboardSupport" i noticed:
```

PHP message: PHP Warning:  Trying to access array offset on value of type int in /var/www/app/plugins/KanboardSupport/Template/config/support.php on line 30",
PHP message: PHP Warning:  Undefined array key "HTTPS" in /var/www/app/plugins/KanboardSupport/Template/config/support.php on line 488",
PHP message: PHP Warning:  Undefined array key "SCRIPT_URI" in /var/www/app/plugins/KanboardSupport/Template/config/support.php on line 45",
PHP message: PHP Warning:  Undefined array key "HTTP_MOD_REWRITE" in /var/www/app/plugins/KanboardSupport/Template/config/support.php on line 474"
```

**Comment by aljawaid** [comment]
I get the impression the errors you get that I don't are php version differences

**Comment by creecros** [comment]
> I get the impression the errors you get that I don't are php version differences

Switched to lower version:
```
Configuration
Application version: v1.2.20
PHP version: 7.4.19
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 5.10.102.1-microsoft-standard-WSL2
Database driver: sqlite
Database version: 3.34.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
```

Still same errors.

**Comment by creecros** [comment]
also, these are stderr logs.

`
2022/12/28 18:15:22 [error] 15#15: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type int in /var/www/app/plugins/KanboardSupport/Template/config/support.php on line 30PHP message: PHP Notice:  Undefined index: SCRIPT_URI in /var/www/app/plugins/KanboardSupport/Template/config/support.php on line 45PHP message: PHP Notice:  Undefined index: HTTP_MOD_REWRITE in /var/www/app/plugins/KanboardSupport/Template/config/support.php on line 474PHP message: PHP Notice:  Undefined index: HTTPS in /var/www/app/plugins/KanboardSupport/Template/config/support.php on line 488" while reading response header from upstream, client: 172.17.0.1, server: localhost, request: "GET /settings/support HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.2:41111"`

not sure they would show up in apache error logs unless you have done something to make them show up. you can test, by making an intentional error, and see if 
![image](https://user-images.githubusercontent.com/26339368/209855729-445fabb2-6a75-4952-919a-b0985658ec07.png)
shows up in your logs.
