### ISSUE TITLE
Request: Add New Colours to Extra Colour Palette

### ISSUE THREAD

**Issue by JustFxDev** [aljawaid/ColorManager#20]
Hi aljawid,

i really love that plug in. The extened palette is directly available in the selection dropdown in the task and it shows an example right in the drop down fields  👍  🥇 

I have a smal enhancement request: can you add an all white color box the the selection? Border white and background white.

I'am working an a theme which shows color only on the left side in the border. And i would be able to have no border shown. It's like the wekan theme works with coloring tasks.

It would have the same effect in that theme.

When i set default to White:White (when available) i have an uncolored task on the borad. Without the need to create upfront such a color in the user specific section.

At the moment i get a gray left border when i use White as default (which is correct because of the gray border definition for white)!

![grafik](https://user-images.githubusercontent.com/82320201/210077925-9238be44-06ec-44b0-80f5-e0ea1906371e.png)

Cheers, Fx

**Comment by JustFxDev** [comment]
Yes, i know i can add a custom color White:White, but i want to avoid that.

**Comment by aljawaid** [comment]
> i really love that plug in. The extened palette is directly available in the selection dropdown in the task and it shows an example right in the drop down fields 👍 🥇
- thanks... the biggest functionality came from @creecros, the dropdown was annoying me so me and @creecros had to do something about it... it is all in line with GTD... which is what Kanboard and Kanban is all about.... hence my Glancer plugin

> I have a smal enhancement request: can you add an all white color box the the selection? Border white and background white.
ooooh... give me at least 5 new colours if you want me to extend the palette... I stopped at 50, although I use around 47 of them in my tags....
1. White:White - Pure white (white border, white background, black text)

**Comment by JustFxDev** [comment]
> 1. White:White - Pure white (white border, white background, black text)

Yes, just like the existing "White" but also with a white border.

![grafik](https://user-images.githubusercontent.com/82320201/210089919-21696cf7-6472-4a36-8efa-eba67fecc4dd.png)

**Comment by aljawaid** [comment]
1. Bright White (white background, white border, black text)
2. Grey on Black (black background, grey text, black border)
3. Grey on Black Border (black background, grey text, grey border)
4. .
5. .

@JustFxDev any others you may need?  I dont want to add less than 5 new colours, so if you need 2 more, add here, otherwise let me know and I will create 2 new ones myself.

**Comment by JustFxDev** [comment]
What about just removing "Bright Yellow" which is very close to Kanboards default  yellow or default lime and just adding Bright white?

I think the color selection of th Extra Palette is absolut ok regarding the amount of choices.

But if you like: just add two more on your own 😄

**Comment by aljawaid** [comment]
> What about just removing "Bright Yellow" which is very close to Kanboards default  yellow or default lime and just adding Bright white?
> 
> I think the color selection of th Extra Palette is absolut ok regarding the amount of choices.
> 
> But if you like: just add two more on your own 😄 
> 
> 

Nooooo.... Bright yellow is used in one of my tags but it shouldn't be 'very' close. I need to look into that.
