### ISSUE TITLE
Translation of color names

### ISSUE THREAD

**Issue by JustFxDev** [aljawaid/ColorManager#22]
Hi aljawaid,
 the colors in the Kanboard core are translated (while not using the ColorManager)
 

Kanboard
 
![grafik](https://user-images.githubusercontent.com/82320201/210085650-f81be84d-f2d0-458e-81e5-80426ea6b54b.png)

Kanboard with ColorManager

![grafik](https://user-images.githubusercontent.com/82320201/210085852-ba861257-c052-422d-90c3-c49d2516f36a.png)

I could not easly figure out where to change that in the code.

Any hints?

Cheers, Fx

**Comment by aljawaid** [comment]
hello, interesting, I didnt realise the names from the default palette were translated.  I did check at the start of the plugin, but I will have another look.

My palette is not translatable through the code. Not yet anyway.

**Comment by JustFxDev** [comment]
Yes, i saw that. Just in that moment i see it's mixed in the drop down: german words for the core colors and english for the CM colors... 😄 

![grafik](https://user-images.githubusercontent.com/82320201/210089348-1267bdd2-a419-4d19-8cd0-08bea2acc053.png)

**Comment by aljawaid** [comment]
I found the issue, I will fix it.

The list will be translatable, but the ColorManager settings page will only show English colour names due to the way it is sorted (by name). But in the tooltip, I have managed to translate it, so it is kind of the best of both worlds.

**Comment by JustFxDev** [comment]
> The list will be translatable, but the ColorManager settings page will only show English colour names due to the way it is sorted (by name). But in the tooltip, I have managed to translate it, so it is kind of the best of both worlds.

Sound good. I don't care whats in the backend.

Thanks 👍
