### ISSUE TITLE
Bug: Long Colour Names Show Incorrectly in Select2 Dropdown

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ColorManager#31]
![image](https://user-images.githubusercontent.com/10233708/211181406-57fd0879-97ba-432f-9ad8-adce480e499a.png)

**Comment by creecros** [comment]
call it royal blue.  should shorten it enough to fit. never heard of supreme blue anyway, and I'm in graphic Communications by trade. but, something to think about for translations, if these names are too long they shift down a line.

**Comment by creecros** [comment]
I'd also call Red Orange, which I've never heard of, Clemson Orange. Just because...
![image](https://user-images.githubusercontent.com/26339368/211196047-f0cb45c3-30a5-4366-b29d-58ec1074e5b8.png)
