### ISSUE TITLE
Rename Long Colours

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ColorManager#33]
call it royal blue.  should shorten it enough to fit. never heard of supreme blue anyway, and I'm in graphic Communications by trade. but, something to think about for translations, if these names are too long they shift down a line.

_Originally posted by @creecros in https://github.com/aljawaid/ColorManager/issues/31#issuecomment-1374823944_

**Comment by aljawaid** [comment]
@creecros Can you please have a look at the other colour names too?

I got most of the names from color-name.com

**Comment by aljawaid** [comment]
@creecros Clemson Orange just seems to be for Clemson Tigers... if you search by HEX code, it just shows up as Orange across the web.

**Comment by creecros** [comment]
I bleed orange, so it's the only orange I care about. go tigers!

**Comment by aljawaid** [comment]
> I bleed orange, so it's the only orange I care about. go tigers!
That sounds dangerous for halloween lol
