### ISSUE TITLE
BUG: Font Colour will Cause Errors

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ColorManager#7]
Colours using font colours are check as `if` but should be `isset`

- Add font colour to relevant colour as normal in the model
- **Check using `isset`** before using it

Code Issues:
- 0a74028 Add 3 Colours 
- 9cc4ce7 Add html entity for white text indication in dropdowns 
- 57913fe Add Font Color

**Comment by aljawaid** [comment]
@creecros I have changed the code, please check if any errors on your side before I go further with the plugin

**Comment by aljawaid** [comment]
> @creecros I have changed the code, please check if any errors on your side before I go further with the plugin

my error log is fine, so unless you tell me something... the `issets` worked fine

**Comment by creecros** [comment]
no errors, but the font colors are ignored, which i would say defeats the purpose.

**Comment by aljawaid** [comment]
> no errors, but the font colors are ignored, which i would say defeats the purpose.
> 
ah ok, that would be missing css, I will look into it.  it work on tags and i been focussing on that.

**Comment by creecros** [comment]
looking at the console, it's not missing but the font color is being trumped by other css.

**Comment by aljawaid** [comment]
> looking at the console, it's not missing but the font color is being trumped by other css.

yes, i just had a quick look, certain classes to be overridden in the plugin are missing on my side... kanboard core is the classes you are seeing...
